### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by ASmyrnyi** [FranjeGueje/DeckTools#3]
Please add support for other languages (english, at least)

**Comment by FranjeGueje** [comment]
Hi,
I think that Steamapps Cleaner is in Spanish and English. 

This app check the LANG variable and show the locate correctly.

Can you check your LANG variable? Please run in console:
echo $LANG

and please, let me know the var and app locale.

Best regards

**Comment by ASmyrnyi** [comment]
I meant not only the UI but full translation, for example Titles (Desconocido) or Previously (¿?)

**Comment by FranjeGueje** [comment]
Ok. I'll review it.
:)

**Comment by FranjeGueje** [comment]
Hi,
I've launched the 2.3 version. I checked all the texts. I hope I have not left any out.

Best regards
